# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../src/rightClickHelper/view/management/dialog/editMenuItemCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 300)
        Dialog.setStyleSheet("#Dialog {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#content {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.content = QtWidgets.QWidget(Dialog)
        self.content.setGeometry(QtCore.QRect(10, 10, 340, 280))
        self.content.setStyleSheet("#confirm, #cancle {\n"
"    height: 25px;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#confirm {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(85, 170, 255);\n"
"    background-color: rgb(64, 158, 255);\n"
"}\n"
"#confirm:hover {\n"
"    border: 1px solid rgb(102, 177, 255);\n"
"    background-color: rgb(102, 177, 255);\n"
"}\n"
"\n"
"#cancle {\n"
"    border: 1px solid rgb(220, 223, 230);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#cancle:hover {\n"
"    color: rgb(64, 169, 255);\n"
"    border: 1px solid rgb(198, 226, 255);\n"
"    background-color: rgb(236, 245, 255);\n"
"}")
        self.content.setObjectName("content")
        self.bottom = QtWidgets.QWidget(self.content)
        self.bottom.setGeometry(QtCore.QRect(10, 220, 321, 61))
        self.bottom.setObjectName("bottom")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.bottom)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 321, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.bottomHL = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.bottomHL.setContentsMargins(20, 0, 20, 0)
        self.bottomHL.setSpacing(40)
        self.bottomHL.setObjectName("bottomHL")
        self.cancle = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        self.cancle.setFont(font)
        self.cancle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancle.setObjectName("cancle")
        self.bottomHL.addWidget(self.cancle)
        self.confirm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        self.confirm.setFont(font)
        self.confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm.setObjectName("confirm")
        self.bottomHL.addWidget(self.confirm)
        self.menuItem = QtWidgets.QWidget(self.content)
        self.menuItem.setGeometry(QtCore.QRect(10, 10, 321, 211))
        self.menuItem.setMinimumSize(QtCore.QSize(120, 180))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.menuItem.setFont(font)
        self.menuItem.setStyleSheet("#icon {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.menuItem.setObjectName("menuItem")
        self.icon = QtWidgets.QLabel(self.menuItem)
        self.icon.setGeometry(QtCore.QRect(10, 10, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(10)
        self.icon.setFont(font)
        self.icon.setAlignment(QtCore.Qt.AlignCenter)
        self.icon.setObjectName("icon")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.menuItem)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 0, 231, 101))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.cancle.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancle.setText(_translate("Dialog", "取消"))
        self.confirm.setText(_translate("Dialog", "确认"))
        self.icon.setText(_translate("Dialog", "应用无图标"))
        self.label.setText(_translate("Dialog", "标题"))
        self.label_2.setText(_translate("Dialog", "菜单名"))
