# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../src/rightClickHelper/view/management/dialog/editMenuItemCard.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 300)
        Dialog.setStyleSheet("#Dialog {\n"
"    background-color: rgb(0, 0, 0);\n"
"}\n"
"\n"
"#content {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(255, 255, 255);\n"
"}")
        self.content = QtWidgets.QWidget(Dialog)
        self.content.setGeometry(QtCore.QRect(10, 10, 460, 280))
        self.content.setStyleSheet("#closeWindow {\n"
"    border: none;\n"
"    border-image: url(:/ico/image/common-icon/close.png);\n"
"}\n"
"#closeWindow:hover {\n"
"    border-image: url(:/ico/image/common-icon/close-ed.png);\n"
"}\n"
"\n"
"#confirm, #cancle {\n"
"    height: 25px;\n"
"    border: none;\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"#confirm {\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(85, 170, 255);\n"
"    background-color: rgb(64, 158, 255);\n"
"}\n"
"#confirm:hover {\n"
"    border: 1px solid rgb(102, 177, 255);\n"
"    background-color: rgb(102, 177, 255);\n"
"}\n"
"\n"
"#cancle {\n"
"    border: 1px solid rgb(220, 223, 230);\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#cancle:hover {\n"
"    color: rgb(64, 169, 255);\n"
"    border: 1px solid rgb(198, 226, 255);\n"
"    background-color: rgb(236, 245, 255);\n"
"}\n"
"\n"
"QLineEdit {\n"
"    padding-left: 8px;\n"
"    padding-top: 4px; padding-bottom: 4px;\n"
"\n"
"    border-radius: 4px;\n"
"    border: 1px solid rgb(220, 223, 230);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 1px solid rgb(64, 158, 255);\n"
"}")
        self.content.setObjectName("content")
        self.bottom = QtWidgets.QWidget(self.content)
        self.bottom.setGeometry(QtCore.QRect(10, 230, 441, 51))
        self.bottom.setObjectName("bottom")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.bottom)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 441, 51))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.bottomHL = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.bottomHL.setContentsMargins(40, 0, 40, 0)
        self.bottomHL.setSpacing(80)
        self.bottomHL.setObjectName("bottomHL")
        self.cancle = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        self.cancle.setFont(font)
        self.cancle.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancle.setObjectName("cancle")
        self.bottomHL.addWidget(self.cancle)
        self.confirm = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(8)
        self.confirm.setFont(font)
        self.confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm.setObjectName("confirm")
        self.bottomHL.addWidget(self.confirm)
        self.menuItem = QtWidgets.QWidget(self.content)
        self.menuItem.setGeometry(QtCore.QRect(10, 40, 441, 191))
        self.menuItem.setMinimumSize(QtCore.QSize(120, 180))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.menuItem.setFont(font)
        self.menuItem.setStyleSheet("#icon {\n"
"    border-radius: 10px;\n"
"    background-color: rgb(240, 240, 240);\n"
"}")
        self.menuItem.setObjectName("menuItem")
        self.icon = QtWidgets.QLabel(self.menuItem)
        self.icon.setGeometry(QtCore.QRect(0, 0, 81, 81))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei")
        font.setPointSize(10)
        self.icon.setFont(font)
        self.icon.setAlignment(QtCore.Qt.AlignCenter)
        self.icon.setObjectName("icon")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.menuItem)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(90, 0, 351, 91))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.topInputs = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.topInputs.setContentsMargins(5, 5, 5, 5)
        self.topInputs.setSpacing(5)
        self.topInputs.setObjectName("topInputs")
        self.titleInputHL = QtWidgets.QHBoxLayout()
        self.titleInputHL.setObjectName("titleInputHL")
        self.titleInputLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.titleInputLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.titleInputLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.titleInputLabel.setFont(font)
        self.titleInputLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.titleInputLabel.setObjectName("titleInputLabel")
        self.titleInputHL.addWidget(self.titleInputLabel)
        self.titleInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.titleInput.setFont(font)
        self.titleInput.setObjectName("titleInput")
        self.titleInputHL.addWidget(self.titleInput)
        self.topInputs.addLayout(self.titleInputHL)
        self.menuNameHL = QtWidgets.QHBoxLayout()
        self.menuNameHL.setObjectName("menuNameHL")
        self.menuNameLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.menuNameLabel.setMinimumSize(QtCore.QSize(50, 0))
        self.menuNameLabel.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.menuNameLabel.setFont(font)
        self.menuNameLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.menuNameLabel.setObjectName("menuNameLabel")
        self.menuNameHL.addWidget(self.menuNameLabel)
        self.menuNameInput = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.menuNameInput.setFont(font)
        self.menuNameInput.setObjectName("menuNameInput")
        self.menuNameHL.addWidget(self.menuNameInput)
        self.topInputs.addLayout(self.menuNameHL)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.menuItem)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(0, 90, 441, 51))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.bottomInputs = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.bottomInputs.setContentsMargins(5, 5, 5, 5)
        self.bottomInputs.setSpacing(5)
        self.bottomInputs.setObjectName("bottomInputs")
        self.commandInputHL = QtWidgets.QHBoxLayout()
        self.commandInputHL.setObjectName("commandInputHL")
        self.commandLabel = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.commandLabel.setMinimumSize(QtCore.QSize(72, 0))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.commandLabel.setFont(font)
        self.commandLabel.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.commandLabel.setObjectName("commandLabel")
        self.commandInputHL.addWidget(self.commandLabel)
        self.commandInput = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.commandInput.setFont(font)
        self.commandInput.setObjectName("commandInput")
        self.commandInputHL.addWidget(self.commandInput)
        self.bottomInputs.addLayout(self.commandInputHL)
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.menuItem)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(0, 140, 441, 51))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.btnsHL = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.btnsHL.setContentsMargins(0, 0, 0, 0)
        self.btnsHL.setObjectName("btnsHL")
        self.btns = QtWidgets.QWidget(self.horizontalLayoutWidget_4)
        self.btns.setStyleSheet("QPushButton {\n"
"    border:  none;\n"
"}\n"
"\n"
"#shift {\n"
"    border-image: url(:/icon/image/shift-key.png);\n"
"}\n"
"#shift[status=\'open\'] {\n"
"    border-image: url(:/icon/image/shift-key-sel.png);\n"
"}\n"
"\n"
"#explorer {\n"
"    border-image: url(:/icon/image/explorer.png);\n"
"}\n"
"#explorer[status=\'open\'] {\n"
"    border-image: url(:/icon/image/explorer-sel.png);\n"
"}\n"
"\n"
"#notCurWorkDir {\n"
"    border-image: url(:/icon/image/not-cur-work-dir.png);\n"
"}\n"
"#notCurWorkDir[status=\'open\'] {\n"
"    border-image: url(:/icon/image/cur-work-dir.png);\n"
"}")
        self.btns.setObjectName("btns")
        self.shift = QtWidgets.QPushButton(self.btns)
        self.shift.setGeometry(QtCore.QRect(10, 10, 48, 30))
        self.shift.setMinimumSize(QtCore.QSize(20, 20))
        self.shift.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.shift.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.shift.setText("")
        self.shift.setObjectName("shift")
        self.explorer = QtWidgets.QPushButton(self.btns)
        self.explorer.setGeometry(QtCore.QRect(80, 10, 31, 31))
        self.explorer.setMinimumSize(QtCore.QSize(20, 20))
        self.explorer.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.explorer.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.explorer.setText("")
        self.explorer.setObjectName("explorer")
        self.notCurWorkDir = QtWidgets.QPushButton(self.btns)
        self.notCurWorkDir.setGeometry(QtCore.QRect(130, 10, 31, 31))
        self.notCurWorkDir.setMinimumSize(QtCore.QSize(20, 20))
        self.notCurWorkDir.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.notCurWorkDir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.notCurWorkDir.setText("")
        self.notCurWorkDir.setObjectName("notCurWorkDir")
        self.btnsHL.addWidget(self.btns)
        self.closeWindow = QtWidgets.QPushButton(self.content)
        self.closeWindow.setGeometry(QtCore.QRect(430, 10, 20, 20))
        self.closeWindow.setMinimumSize(QtCore.QSize(20, 20))
        self.closeWindow.setMaximumSize(QtCore.QSize(20, 20))
        self.closeWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.closeWindow.setText("")
        self.closeWindow.setObjectName("closeWindow")
        self.title = QtWidgets.QLabel(self.content)
        self.title.setGeometry(QtCore.QRect(10, 0, 421, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.title.setFont(font)
        self.title.setObjectName("title")

        self.retranslateUi(Dialog)
        self.cancle.clicked.connect(Dialog.close)
        self.closeWindow.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.cancle.setText(_translate("Dialog", "取消"))
        self.confirm.setText(_translate("Dialog", "确认"))
        self.icon.setText(_translate("Dialog", "应用无图标"))
        self.titleInputLabel.setText(_translate("Dialog", "标题"))
        self.menuNameLabel.setText(_translate("Dialog", "菜单名"))
        self.commandLabel.setToolTip(_translate("Dialog", "点击菜单调用的程序"))
        self.commandLabel.setText(_translate("Dialog", "点击指令"))
        self.shift.setToolTip(_translate("Dialog", "按下shift键时展示"))
        self.explorer.setToolTip(_translate("Dialog", "只在文件浏览器中展示"))
        self.notCurWorkDir.setToolTip(_translate("Dialog", "以当前文件夹为工作目录"))
        self.title.setText(_translate("Dialog", "标题"))
from src.resource import main_rc
