# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '../src/rightClickHelper/view/management/index.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_management(object):
    def setupUi(self, management):
        management.setObjectName("management")
        management.resize(1100, 649)
        management.setMinimumSize(QtCore.QSize(1100, 649))
        management.setMaximumSize(QtCore.QSize(1100, 650))
        management.setStyleSheet("QScrollBar:vertical {\n"
"    background-color: rgb(250, 250, 250);\n"
"    width: 6px;\n"
"    margin: 0px;border: none;\n"
"}\n"
"QScrollBar::handle:vertical {\n"
"    background-color: rgb(216, 216, 216);\n"
"    min-height: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:vertical:hover{background-color: rgb(181, 181, 181);}\n"
"QScrollBar:horizontal {\n"
"    background-color: rgb(250, 250, 250);\n"
"    height: 6px;\n"
"    margin: 0px;border: none;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background-color: rgb(216, 216, 216);\n"
"    min-width: 5px;\n"
"    border-radius: 3px;\n"
"}\n"
"QScrollBar::handle:horizontal:hover{background-color: rgb(181, 181, 181);}\n"
"\n"
"QScrollBar::up-arrow, QScrollBar::down-arrow,\n"
"QScrollBar::right-arrow, QScrollBar::left-arrow,\n"
"QScrollBar::add-page, QScrollBar::sub-page,\n"
"QScrollBar::add-line, QScrollBar::sub-line {\n"
"    border: none;background: none;color: none;height: 0;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(management)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 1091, 641))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.management_w = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.management_w.setContentsMargins(0, 0, 0, 0)
        self.management_w.setSpacing(5)
        self.management_w.setObjectName("management_w")
        self.head = QtWidgets.QWidget(self.verticalLayoutWidget)
        self.head.setObjectName("head")
        self.searchInput = QtWidgets.QLineEdit(self.head)
        self.searchInput.setGeometry(QtCore.QRect(690, 10, 191, 21))
        self.searchInput.setObjectName("searchInput")
        self.searchLabel = QtWidgets.QLabel(self.head)
        self.searchLabel.setGeometry(QtCore.QRect(660, 10, 31, 21))
        font = QtGui.QFont()
        font.setFamily("Microsoft JhengHei UI")
        font.setPointSize(10)
        self.searchLabel.setFont(font)
        self.searchLabel.setObjectName("searchLabel")
        self.selKind = QtWidgets.QComboBox(self.head)
        self.selKind.setGeometry(QtCore.QRect(890, 10, 161, 21))
        self.selKind.setObjectName("selKind")
        self.selKind.addItem("")
        self.selKind.addItem("")
        self.selKind.addItem("")
        self.selKind.addItem("")
        self.selKind.addItem("")
        self.currentRegPath = QtWidgets.QLabel(self.head)
        self.currentRegPath.setGeometry(QtCore.QRect(70, 10, 581, 20))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.currentRegPath.setFont(font)
        self.currentRegPath.setObjectName("currentRegPath")
        self.pushButton = QtWidgets.QPushButton(self.head)
        self.pushButton.setGeometry(QtCore.QRect(10, 10, 20, 20))
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.head)
        self.pushButton_2.setGeometry(QtCore.QRect(40, 10, 20, 20))
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.management_w.addWidget(self.head)
        self.itemScrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.itemScrollArea.setStyleSheet("#itemScrollArea {\n"
"    border: none;\n"
"    background-color: rgb(250, 250, 250);\n"
"}\n"
"\n"
"#itemScrollAreaWidget {\n"
"    background-color: rgb(250, 250, 250);\n"
"}")
        self.itemScrollArea.setWidgetResizable(True)
        self.itemScrollArea.setObjectName("itemScrollArea")
        self.itemScrollAreaWidget = QtWidgets.QWidget()
        self.itemScrollAreaWidget.setGeometry(QtCore.QRect(0, 0, 1089, 594))
        self.itemScrollAreaWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.itemScrollAreaWidget.setAutoFillBackground(True)
        self.itemScrollAreaWidget.setObjectName("itemScrollAreaWidget")
        self.itemScrollArea.setWidget(self.itemScrollAreaWidget)
        self.management_w.addWidget(self.itemScrollArea)
        self.management_w.setStretch(0, 1)
        self.management_w.setStretch(1, 15)

        self.retranslateUi(management)
        QtCore.QMetaObject.connectSlotsByName(management)

    def retranslateUi(self, management):
        _translate = QtCore.QCoreApplication.translate
        management.setWindowTitle(_translate("management", "Form"))
        self.searchLabel.setText(_translate("management", "搜索"))
        self.selKind.setItemText(0, _translate("management", "文件"))
        self.selKind.setItemText(1, _translate("management", "文件夹"))
        self.selKind.setItemText(2, _translate("management", "目录"))
        self.selKind.setItemText(3, _translate("management", "目录背景"))
        self.selKind.setItemText(4, _translate("management", "桌面背景"))
        self.currentRegPath.setText(_translate("management", "文件夹/"))
from src.resource import main_rc
